// Mock data for testing when Supabase is not available
export const mockStates = [
  'U.P.',
  'M.P.',
  'Delhi',
  'Bangalore',
  'Mumbai',
  'Kolkata',
  'Chennai',
  'Pune',
  'Hyderabad',
  'Jaipur',
  'Lucknow',
  'Ahmedabad',
  'Surat',
  'Nagpur',
  'Indore',
  'Thane',
  'Bhopal',
  'Visakhapatnam',
  'Patna',
  'Vadodara',
  'Agra',
  'Nashik',
  'Faridabad',
  'Meerut',
  'Rajkot',
  'Kalyan-Dombivali',
  'Vasai-Virar',
  'Varanasi',
  'Srinagar',
  'Dhanbad',
  'Jodhpur',
  'Amritsar',
  'Raipur',
  'Allahabad',
  'Coimbatore',
  'Jabalpur',
  'Gwalior',
  'Vijayawada',
  'Madurai',
  'Guwahati',
  'Chandigarh',
  'Hubli-Dharwad',
  'Mysore',
  'Tiruchirappalli',
  'Nellore',
  'Thiruvananthapuram',
  'Bhiwandi',
  'Saharanpur',
  'Gulbarga',
  'Navi Mumbai',
  'Kochi',
  'Kozhikode',
  'Kurnool',
  'Bellary',
  'Bikaner',
  'Gwalior',
  'Ajmer',
  'Kolhapur',
  'Latur',
  'Nanded',
  'Ongole',
  'Tirupati',
  'Rourkela',
  'Bhilai',
  'Korba',
  'Bhilwara',
  'Ratlam',
  'Mathura'
];

export const mockAuditLogs = [
  {
    id: '1',
    action_type: 'STATE_MAPPING_UPDATE',
    table_name: 'creators',
    record_id: 'U.P.',
    old_value: 'U.P.',
    new_value: 'Uttar Pradesh',
    user_email: 'admin@example.com',
    ip_address: '127.0.0.1',
    timestamp: new Date().toISOString(),
    metadata: { confidence: 95, autoSelected: true }
  },
  {
    id: '2',
    action_type: 'STATE_MAPPING_UPDATE',
    table_name: 'creators',
    record_id: 'M.P.',
    old_value: 'M.P.',
    new_value: 'Madhya Pradesh',
    user_email: 'admin@example.com',
    ip_address: '127.0.0.1',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    metadata: { confidence: 92, autoSelected: true }
  }
];

export const mockUser = {
  id: 'mock-user-id',
  email: 'admin@example.com',
  role: 'admin'
};
